### ISSUE TITLE
 Inquiry about Singapore's data

### ISSUE THREAD

**Issue by hxTrans** [gilbertocortez/Solar_API_Library#1]
Thank you for your excellent work! Could you please confirm if the geotiff data is accessible for Singapore? While attempting to locate the address in Singapore, I'm unable to see the overlaid annual flux layer.

**Comment by gilbertocortez** [comment]
I do not believe so, you can see a map of the areas with coverage at: https://developers.google.com/maps/documentation/solar/coverage

Marking as resolved, let me know if you have any more questions
